# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------
include(../../gui.pro.tpl)

TEMPLATE = app
TARGET = sgrenderertest$$LIB_SUFFIX
DESTDIR = ./linux/bin
QT += core qtmain
CONFIG(debug, debug|release) {
#        DEFINES += QT_LARGEFILE_SUPPORT
} else {
#        DEFINES += QT_LARGEFILE_SUPPORT
}

target.path += ../../../../build/bin
INSTALLS += target

USER_CXXFLAGS := -I
USER_LDFLAGS := 


INCLUDEPATH += ./GeneratedFiles/Debug \
               ./../graphbase \
               ./../renderer \
               ./.. \
               ../../../thirdParty/gtest-1.4.0/include

LIBS += -L/home/builder/thirdParty/linux/gtest/lib \
        -L"./../linux/lib" \
        -lsgrendererd \
        -lgtest

QMAKE_RPATHDIR += ./../../util/xmlHelper/linux/lib \
                  ./../../util/util/linux/lib \
                  /home/builder/thirdParty/linux/xerces27/lib_gcc4 \
                  /home/builder/thirdParty/linux/tcl8.5.3/lib

QMAKE_LFLAGS += -Wl,-E

include(test.pri)
