# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./tst_grhagl.h

SOURCES += ./main.cpp


