######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 15 16:27:34 2011
######################################################################

TEMPLATE = app
TARGET = viewer
DEPENDPATH += . debug tmp\rcc\release_shared
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += glwidget.h mainwindow.h
SOURCES += glwidget.cpp main.cpp mainwindow.cpp
RESOURCES += dockwidgets.qrc
