BIN    = test_lc2kdtree.exe
OBJS   = sgr_lc.o test_lc2kdtree.o sgr_lc2kdtree.o
SRC    = $(OBJS:%.o=%.cpp)
INC    = $(OBJS:%.o=%.h)
CXX     = g++
CXXFLAGS = -c -g
LINKOPT = 
INCPATH = -I"../../graphbase"

all : $(BIN)

$(BIN) : $(OBJS)
	$(CXX) $(OBJS) -o $(BIN) $(LINKOPT)

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

clean :
	rm -rf *.o
	rm -rf *.exe

install : install.bin

install.bin :
	cp *.exe ../../build/bin

