BIN    = test_vfculler.exe
OBJS   = sgr_lc.o test_vfculler.o sgr_vfculler.o ../../graphbase/sgr_math.o sgr_bboxupdater.o sgr_lcreport.o
SRC    = $(OBJS:%.o=%.cpp)
INC    = $(OBJS:%.o=%.h)
CXX     = g++
CXXFLAGS = -c -g
LINKOPT = 
INCPATH = -I"../../graphbase" -I"."

all : $(BIN)

$(BIN) : $(OBJS)
	$(CXX) $(OBJS) -o $(BIN) $(LINKOPT)

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

clean :
	rm -rf *.o
	rm -rf *.exe

install : install.bin

install.bin :
	cp *.exe ../../build/bin

